#+title: Todo
* [X] Add public OpenAI API call definitions for existing tools
* [X] Add language to symbol and use it find parser when generating a summary
* [X] Fix python decorators to be included in raw symbol output
* [X] Implement recursive parsing function. Do not parse the file if it's hash did not change.
* [X] Add data access helper that reads file from data store along with all symbols
* [X] Add a helper to resolve import edge dependencies
* [X] Need to delete files, packages, symbols, etc that are no longer exist on the disk
* [X] Create helper methods to return models from parser objects
* [X] Fix _resolve_to_package_id to use data repository
* [X] Figure out a way to call functions for language parsers after finishing parsing files
* [ ] Language support
** [X] Golang
*** [X] When parsing golang methods, link these symbols back to structure that should be defined in the same package.
** [ ] C
** [ ] JavaScript
** [ ] TypeScript
** [ ] Java
** [ ] C#
** [ ] PHP
** [ ] Rust
** [ ] Zig
** [ ] C++
* [ ] Documentation generator
* [ ] CI/CD pipeline
* [ ] Add git support
** [ ]  Use git to quickly find what files have changed
* [X] Expose a helper method in Project class to calculate embedding for the arbitrary search term
* [X] Better in-memory vector index for faster lookups
* [X] Separate embeddings from primary data store
* [X] Create a helper that generates a summary view of a file
* [ ] MCP-compatible tool definition support
* [X] Tools
** [X] File list
** [X] Summary lists
- Takes a list of file paths or packages
- Returns summary views of files
** [X] Get full files
- A list of files
** [X] Search through symbols
- Needle
- Result list
* [X] Figure out a way to update embeddings in background
* [X] Add embedding value caching
** [X] A shared cross-project table
* [ ] A server with simple API to insert embedding value for a hash and get multiple embedding values for a hash
* [X] Do not warn on python pass_statement
* [ ] Add support for Python del_statement?
* [X] Add support for FTS when embedding search is not feasible
* [X] Even if file can not be parsed, store information about it in the database
* [X] When reparsing file and symbols did not change - do not recalculate embeddings
* [X] Build a tool that provides recommendations for a list of files/packages by applying PageRank algorithm to dependencies.
* [X] Add package_id to symbols to speed up search
* [X] Add caching for go.mod at project level to avoid loading it for each and every Go file
* [ ] Do not refresh DuckDB index if project did not change
* [X] Figure out a way to have a single query parameter that searches code by embedding and documentation. Idea: calculate embedding vector for commend/docstring and use that instead of FTS. Fallback to FTS if embeddings are not enabled.
* [X] Add symbol search test
* [ ] Add reranking model support
* [X] Python parser should preserve decorators when parsing symbols. Extend model to collect decorators and store them in model.
* [X] Python parser does not parse symbols of decorated methods
* [ ] When including child symbols, pass visibility mode from parent query. Do not include private methods for publicly requested symbols.
* [X] Search for public symbols by default
* [X] Recommendation engine
** [X] Store all references for each file
- New model
- Include import information, if it can be resolved
** [X] Create in-memory NetworkX graph
- Add all project public symbols and all references
- Implement ranking algorithm to find recommendations
** [X] Figure out incremental graph updates
** [X] Create a tool that takes in file paths, query, runs above algorithm
* [ ] Add infra to maintain in-memory tools like RepoMap
** [ ] Enable/Disable RepoMap configuration flag
* [ ] Create a simple web ui to navigate project database
* [ ] Validate traversal logic to ensure we can not go outside of the project directory.
* [X] Add a way to destroy the project. This should also shutdown/stop embedding worker.
** [X] Add a destory() method to embedding worker
* [ ] Add a way to initialize project, but only scan and work from a subpath
** [ ] Search should be scoped to files in subdirectories
* [X] Strip spaces from multi-line commends, but recover when generating summaries
* [X] Instead of having multiple flags for summary/full/none, add enum to tools
* [X] If embedding model for the vector does not match current embedding model - either update OR skip
* [X] Find a way to de-dupe embedding queue to avoid calculating vectors multiple times
* [ ] Search to support exclude. For example - tests
* [ ] Golang summary optimizations - group multiple var/const definitions into a single block to save on tokens
* [ ] Move file summary helper out of tools
* [ ] Better lookup with filters methods in data layer
