#+title: Todo
* [ ] Change summary API to not return whole file - remove enum.
* [ ] Create a new read file tool
* [ ] Create async API
** [ ] Spin a new thead for the project
** [ ] Create async thread wrappers (use library from Code)

* [ ] Create project-parsing progress callbacks or iterator-based methods
* [ ] Write data model documentation
- signature.raw should include whole signature including name
* [ ] Fix BaseTool definition to accept and return BaseModel (or list of BaseModel for return)
* [X] Initial refresh should reset refresh timer, so next tool run would not do another refresh
* [ ] Add a way to fully disable a tool so it won't register any components
* [X] Investigate Go parser performace
* [ ] Add a way to initialize project, but only scan and work from a subpath
** [ ] Search should be scoped to files in subdirectories
* [ ] Optimize chunker to tokenize and then de-tokenize to generate result, as an optimization?
* [ ] Method to fully reparse the repo in project
* [ ] Storage backends
** [ ] PostgreSQL backend
** [ ] Add Sqlite backend
** [X] Extract common SQL functionality into helper
* [ ] Generic helper to find references using tree sitter query in a generic way
** [ ] Figure out if we want to merge similar references or[fn:1] not
* [ ] Add query timeouts to DuckDB to detect lockups
* [ ] Add a inherits field to symbols and use for classes
** [ ] Update SymbolRef to use these too
* [ ] When parsing references from files, skip duplicate names?
* [ ] Add a way to override file mapping. For example, .h might point to C or ObjC parser.
* [ ] Language support
** [X] Text
*** [X] Recursive splitter by paragraph and then sentence-based splitters.
** [X] Markdown
** [-] Python
*** [X] Test module path resolution
*** [X] Fix to_package_path for python
        to_package_path='os', for 'os.path.join'
*** [ ] Fix summary generator to not include module docstring if level is short summary - add special handling to _handle_expression_string and new node type for documentation
*** [ ] Fix: Parser handled node but produced no symbols line=73 node_type=expression_statement path=tools/mcpserver.py raw='mcp, settings = create_mcp_app()'
*** [X] Add support for for_statement, raise_statement, with_statement
** [X] Golang
*** [X] When parsing golang methods, link these symbols back to structure that should be defined in the same package.
*** [X] Refactror node parser to return nodes like python and typescript parsers
*** [X] Generics
*** [X] Add support for multi-module projects with nested go.mod
** [-] TypeScript
*** [X] Reference parsing
*** [X] Generics
*** [X] Namespaces
*** [X] CommonJS imports and exports
*** [X] Modules
*** [ ] Declare
*** [ ] Test module path resolution
*** [ ] Include extends type to ref results
*** [X] React TSX support
** [X] JavaScript
*** [X] Add support for member_expression, empty_statement node type
*** [X] Add support for statement_block, string, ternary_expression
*** [X] Do not warn on empty_statement
*** [X] Add support for ternary_expression
*** [X] Add support for call_expression
** [ ] HTML
** [ ] C
** [ ] C#
** [X] Java
*** [X] Fix docstring identation for methods
*** [X] Generics
*** [X] Fix enum parsing - methods/constructor should be correctly handled, currently included as literals
*** [X] Add support for module_declaration
*** [X] Add SymbolRef extraction: calls, generic type usage, inheritance
*** [X] Interfaces
*** [X] Annotations
* [ ] Parser fixes
DEBUG:know:2025-08-12 22:10:17 [debug    ] Unknown node                   byte_offset=2674 line=88 path=django/utils/translation/__init__.py raw='del Trans' type=delete_statement
WARNING:know:2025-08-12 22:10:17 [warning  ] Parser handled node but produced no symbols line=84 node_type=expression_statement path=django/contrib/admin/options.py raw='HORIZONTAL, VERTICAL = 1, 2'
DEBUG:know:2025-08-12 22:10:19 [debug    ] No parser registered for path – storing bare File. path=tests/generic_views/templates/generic_views/book_archive_week.html
WARNING:know:2025-08-12 22:10:19 [warning  ] JS parser: unknown class body node class_name=GeometryTypeControl line=4 node_type=comment path=django/contrib/gis/static/gis/js/OLMapWidget.js
* [ ] A server with simple API to insert embedding value for a hash and get multiple embedding values for a hash (share embeddings with a team)
* [ ] Documentation generator
* [ ] CI/CD pipeline
* [ ] Do not refresh DuckDB index if project did not change
* [ ] Improve node search
** [ ] Add reranking model support
* [ ] Validate traversal logic to ensure we can not go outside of the project directory.
* [ ] Search to support exclude. For example - tests
* [ ] Golang summary optimizations - group multiple var/const definitions into a single block to save on tokens
* [ ] When including child symbols, pass visibility mode from parent query. Do not include private methods for publicly requested symbols.
* [ ] Add git support
** [ ]  Use git to quickly find what files have changed?
* [ ] Rename symbols to nodes
* [X] Batch upsert storage support to reduce update latency
** [X] Stores
*** [X] Batch insert
*** [X] Batch update
*** [X] Batch delete
** [X] Batch upsert imports
** [X] Batch delete imports
** [X] Batch insert symbols. Delay embedding scheduling after symbol insert
** [X] Batch insert symbolrefs
* [X] Symbol boosting in search query makes it slow as we need to apply boost each and every field
Optimize by denormalizing boost into separate column. Figure out per-repo boosting.
* [X] Add project-level paths
** [X] If enabled, all virtual paths are prefixed with repo name
** [X] Provide virtual to physical path resolution helper. If not, goes through .virtual-path/ directory
* [X] File summary should return full file if file is not summarized
* [X] Configurable RRF weights
* [X] Auto-refresh
** [X] Auto-refresh on every tool call
** [X] Auto-refresh on tool call, but not more often than every X minutes
** [X] Auto-refresh associated repos or primary repo
* [X] Repomap should ignore non-default repos in the project
* [X] Extend Node to have subtype str type (used for block types, etc)
* [X] Search tool
** [X] Better tokenizer for the fts index (syntax specific?)
*** [X] Per-language stop words?
** [X] Lower weight of literal symbols
** [X] Boost final score of functions/methods/symbol definitions
** [X] Figure out field awareness and ranking
** [X] Make tool search all symbols, not just public by default
** [X] Do not crash if input enums are wrong. ValueError: 'identifier' is not a valid SymbolKind.
* [X] Move some tool parameters to project settings
* [X] Debug search quality
* [X] Move data helpers out of data.py
* [X] Introduce concept of project which is a collection of repositories
** [X] Create virtual path for other repos
** [X] Boost default file suggestions in search, make it configurable
* [X] Fix mypy warnings
* [X] Repomap tool
** [X] Should only look for exported symbols
* [X] Update chat example to use litellm instead of OpenAI API directly
* [X] Cache improvements
** [X] Collect and mass-update embeddings that were recently used
** [X] Add lifecycle rules to cleanup old unused embeddings
* [X] Embedding calculation should include docstring and prior comment
* [X] Add dedicated single-thread worker for DuckDB to work around its thread handling.
* [X] Define the meaning of to_package_path for ParsedSymbolRef (virtual path, physical path, etc)
* [X] No packages should be created for text/rest files
* [X] Embedding priority mode does not run them first
* [X] Delay embeddings calculation until project parsing has finished to unblock token counts
* [X] Refactor symbols
** [X] Everything is a symbol
** [X] Update symbol upsert to work without key. If key is not set, then do matching by content.
** [X] Do insert/delete instead of update?
** [X] Rename to Node
* [X] MCP server
* [X] Add support for Python del_statement, if statement, etc.
* [X] Add infra to maintain in-memory tools like RepoMap
** [X] Enable/Disable tools configuration flag
* [X] Figure out lockup in filelist tool
* [X] DuckDB concurrent writes problem when updating vectors: duckdb.duckdb.TransactionException: TransactionContext Error: Failed to commit: write-write conflict on key
* [X] Only include mentioned symbols in repomap instead of file summary?
* [X] Configuration object
* [X] Measure startup time
* [X] Measure time it takes to process file, a batch of files, etc
* [X] Rewrite SQL backends to use PyPika
* [X] Add public OpenAI API call definitions for existing tools
* [X] Add language to symbol and use it find parser when generating a summary
* [X] Fix python decorators to be included in raw symbol output
* [X] Implement recursive parsing function. Do not parse the file if it's hash did not change.
* [X] Add data access helper that reads file from data store along with all symbols
* [X] Add a helper to resolve import edge dependencies
* [X] Need to delete files, packages, symbols, etc that are no longer exist on the disk
* [X] Create helper methods to return models from parser objects
* [X] Fix _resolve_to_package_id to use data repository
* [X] Figure out a way to call functions for language parsers after finishing parsing files
* [X] Get rid of symbol hashes for short (all?) symbols - just check the body.
* [X] Add a flag to mark symbols as exported instead of treating them as public
* [X] Summary mode where parent symbols are also included
* [X] Move parse() implementation to AbstractCodeparser. Allow to customize.
* [X] Expose a helper method in Project class to calculate embedding for the arbitrary search term
* [X] Better in-memory vector index for faster lookups
* [X] Separate embeddings from primary data store
* [X] Create a helper that generates a summary view of a file
* [X] Tools
** [X] File list
** [X] Summary lists
- Takes a list of file paths or packages
- Returns summary views of files
** [X] Get full files
- A list of files
** [X] Search through symbols
- Needle
- Result list
* [X] Figure out a way to update embeddings in background
* [X] Add embedding value caching
** [X] A shared cross-project table
* [X] Do not warn on python pass_statement
* [X] Add support for FTS when embedding search is not feasible
* [X] Even if file can not be parsed, store information about it in the database
* [X] When reparsing file and symbols did not change - do not recalculate embeddings
* [X] Build a tool that provides recommendations for a list of files/packages by applying PageRank algorithm to dependencies.
* [X] Add package_id to symbols to speed up search
* [X] Add caching for go.mod at project level to avoid loading it for each and every Go file
* [X] Figure out a way to have a single query parameter that searches code by embedding and documentation. Idea: calculate embedding vector for commend/docstring and use that instead of FTS. Fallback to FTS if embeddings are not enabled.
* [X] Add symbol search test
* [X] Python parser should preserve decorators when parsing symbols. Extend model to collect decorators and store them in model.
* [X] Python parser does not parse symbols of decorated methods
* [X] Search for public symbols by default
* [X] Recommendation engine
** [X] Store all references for each file
- New model
- Include import information, if it can be resolved
** [X] Create in-memory NetworkX graph
- Add all project public symbols and all references
- Implement ranking algorithm to find recommendations
** [X] Figure out incremental graph updates
** [X] Create a tool that takes in file paths, query, runs above algorithm
* [X] Create a simple web ui to navigate project database
* [X] Add a way to destroy the project. This should also shutdown/stop embedding worker.
** [X] Add a destory() method to embedding worker
* [X] Strip spaces from multi-line commends, but recover when generating summaries
* [X] Instead of having multiple flags for summary/full/none, add enum to tools
* [X] If embedding model for the vector does not match current embedding model - either update OR skip
* [X] Find a way to de-dupe embedding queue to avoid calculating vectors multiple times
* [X] Move file summary helper out of tools
* [X] Better lookup with filters methods in data layer, similar to symbol search instead of dedicated methods.
* [X] Compress long symbol bodies
